### ISSUE TITLE
Maybe direct memory leak in some extreme situations?

### ISSUE THREAD

**Issue by bluelullaby** [jchambers/pushy#659]
Recently, our production environment has occurred `OutOfDirectMemoryError`, exception stack trace is shown as below (we have increased the max direct memory size up to 500m):

```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 520093975, max: 524288000)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	at com.turo.pushy.apns.ApnsClientHandler.writePushNotification(ApnsClientHandler.java:206)
	at com.turo.pushy.apns.ApnsClientHandler.write(ApnsClientHandler.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:722)
```

I have used Java reflection api to get values of the field `DIRECT_MEMORY_COUNTER` from class `PlatformDependent`, which is a easy way to indicate the direct memory usage.

We haven't changed our code in the production environment for a long time, so I guessed the main reason that caused this problem is the network situation.

Here are the tests I have done:

1. When I sent the push notifications in a slow speed condition (so that every notification can respond rapidly), memory usage works well.

2. In order to simulate the bad network condition, I pushed a mass of notifications in a short time, after receiving all the push notification responses, the value of memory counter cannot restore the initialization.

I have noticed the issue #142 , is this the same problem?

Our production environment `pushy 0.13.1` and `netty 4.1.24.Final`.
I have tested in both `pushy 0.13.1` and `pushy 0.13.6`

Thanks a lot.

**Comment by bluelullaby** [comment]
Thanks for your reply.  I'm sorry that my expression is not clear enough.

1. Yes, your understanding is right. I mean that with sending many notifications, the value of `DIRECT_MEMORY_COUNTER` goes up quickly, but it never comes back down after stopping the pushing action.

2. Here is the condition of our production environment:
    - Running under `pushy 0.13.1` and `netty 4.1.24.Final` (In order to identify the problem, I also have tried to upgrade dependencies to `pushy 0.13.6` and `netty 4.1.28.Final`)  (Oracle Java 1.7.0_07)
    - I've added a function to log the value of `DIRECT_MEMORY_COUNTER` every 5 seconds. 
    - In each pushing action, we send a message to about 150,000 devices. (I set the value of `concurrentConnections` to 8, and pass the new instance of `NioEventLoopGroup` to the client builder, which also holds 8 threads.)
    - Changes in the value of `DIRECT_MEMORY_COUNTER` seem puzzling. The value may go up after a pushing action, but sometimes may not. 

This is the code of the initialization of the `ApnsClient` in our production environment (threadCount = 8):
```java
ApnsClient client = new ApnsClientBuilder()
        .setApnsServer(ApnsClientBuilder.PRODUCTION_APNS_HOST)
        .setClientCredentials(new File(p12File), p12Password)
        .setConcurrentConnections(threadCount)
        .setEventLoopGroup(new NioEventLoopGroup(threadCount))
        .build();
```

3. I also have done some testings to identify the problem:

This code is to log the direct memory usage.

```java
public class MemoryLeakMonitor {

    private static final Logger logger = LoggerFactory.getLogger(MemoryLeakMonitor.class);
    
    private final ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(1);

    private Field field;
    
    public MemoryLeakMonitor() {
        try {
            this.field = PlatformDependent.class.getDeclaredField("DIRECT_MEMORY_COUNTER");
            this.field.setAccessible(true);
        } catch (Exception ignore) { }
    }
    
    public void start() {
        executor.scheduleAtFixedRate(new Runnable() {
            @Override
            public void run() {
                try {
                    AtomicLong counter = (AtomicLong) field.get(null);
                    if (counter != null)
                        logger.info("Current direct memory counter : {} kb.", (counter.get() / 1024));
                } catch (Exception e) {
                    logger.error("Cannot access to the netty memory counter field!!!");
                }
            }
        }, 0, 5, TimeUnit.SECONDS);
    }
    
}
```

This code is the testing code.

```java
public class Application {

    private static final Logger logger = LoggerFactory.getLogger(Application.class);
    
    public static void main(String[] args) throws Exception {
        
        final ApnsClient apnsClient = new ApnsClientBuilder()
                .setApnsServer(ApnsClientBuilder.DEVELOPMENT_APNS_HOST)
                .setClientCredentials(new File("g:/push_apple_development.p12"), "123")
                .setConcurrentConnections(8)
                .build();
        
        MemoryLeakMonitor monitor = new MemoryLeakMonitor();
        monitor.start();

        int i = 0; // send push notifications 10000 times in total
        final AtomicLong cursor = new AtomicLong(0); // cursor of response

        for (;;) {
            
            final ApnsPayloadBuilder payloadBuilder = new ApnsPayloadBuilder();
            payloadBuilder.setAlertBody("Example!");
            
            final String payload = payloadBuilder.buildWithDefaultMaximumLength();
            
            SimpleApnsPushNotification pushNotification = 
                    new SimpleApnsPushNotification("123456789", 
                            "com.example.myApp", payload);
            
            final PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>> 
            sendNotificationFuture = apnsClient.sendNotification(pushNotification);
            
            sendNotificationFuture.addListener(new PushNotificationResponseListener<SimpleApnsPushNotification>() {

                @Override
                public void operationComplete(final PushNotificationFuture<SimpleApnsPushNotification, 
                        PushNotificationResponse<SimpleApnsPushNotification>> future) throws Exception {
                    if (future.isSuccess())
                        logger.info("Receive the {}th response.", cursor.getAndIncrement());
                    else
                        future.cause().printStackTrace();
                }
            });
            
            if (i >= 10000) {
                logger.info("Complete all sending task");
                break;
            }
            
            i++;
            
            Thread.sleep(100);
        }
    }
}
```

When I send the notifications in the low-speed condition (There is 100ms sleep time after each message), the log may like this:

```
[14:37:39:403] Native SSL provider is available; will use native provider.
[14:37:39:534] Current direct memory counter : 16384 kb.
[14:37:40:533] Current direct memory counter : 32768 kb.
[14:37:40:908] Receive the 0th response.
[14:37:40:908] Receive the 1th response.

...

[14:37:41:489] Receive the 17th response.
[14:37:41:533] Current direct memory counter : 32768 kb.
[14:37:41:577] Receive the 18th response.

...

[14:55:50:106] Current direct memory counter : 32768 kb.
[14:55:50:175] Receive the 9995th response.
[14:55:50:258] Complete all sending task
[14:55:50:262] Receive the 9996th response.
[14:55:50:368] Receive the 9997th response.
[14:55:50:468] Receive the 9998th response.
[14:55:51:106] Current direct memory counter : 32768 kb.
[14:55:52:106] Current direct memory counter : 32768 kb.
```

After `ApnsClient` is instantiated, one chunk (16MB) space has been used.
Subsequently, another chunk space is allocated for sending notifications.
Throughout the whole sending task (10,000 messages), the value of `DIRECT_MEMORY_COUNTER` don't increase.

When I comment the last line of the testing code to stop the sleeping operation, as a mass of notifications are sent simultaneously, the direct memory usage goes up, but doesn't come down after the whole sending task. The log may like this:

```
[15:15:43:910] Native SSL provider is available; will use native provider.
[15:15:44:051] Current direct memory counter : 16384 kb.
[15:15:44:278] Complete all sending task
[15:15:45:050] Current direct memory counter : 32768 kb.
[15:15:45:314] Receive the 0th response.
[15:15:45:314] Receive the 1th response.

...

[15:15:46:049] Receive the 1288th response.
[15:15:46:050] Current direct memory counter : 32768 kb.
[15:15:46:050] Receive the 1289th response.

...

[15:15:47:050] Receive the 4110th response.
[15:15:47:051] Current direct memory counter : 49152 kb.
[15:15:47:051] Receive the 4111th response.

...

[15:15:48:017] Receive the 9575th response.
[15:15:48:051] Current direct memory counter : 49152 kb.
[15:15:48:057] Receive the 9576th response.

[15:15:48:188] Receive the 9998th response.
[15:15:48:189] Receive the 9999th response.
[15:15:48:189] Receive the 10000th response.
[15:15:49:051] Current direct memory counter : 49152 kb.
[15:15:50:051] Current direct memory counter : 49152 kb.
```

With the increase of the number of messages to be sent, the memory usage goes up significantly.
This log is the case of sending 50,000 messages:

```
[15:39:57:965] Native SSL provider is available; will use native provider.
[15:39:58:091] Current direct memory counter : 16384 kb.
[15:39:58:549] Complete all sending task
[15:39:59:090] Current direct memory counter : 32768 kb.
[15:39:59:644] Receive the 0th response.
[15:39:59:644] Receive the 1th response

...

[15:40:00:031] Receive the 329th response.
[15:40:00:090] Current direct memory counter : 32768 kb.
[15:40:00:116] Receive the 330th response.

...

[15:40:01:086] Receive the 3120th response.
[15:40:01:090] Current direct memory counter : 49152 kb.
[15:40:01:174] Receive the 3121th response.

...

[15:40:02:058] Receive the 4194th response.
[15:40:02:090] Current direct memory counter : 212992 kb.
[15:40:02:189] Receive the 4195th response.

...

[15:40:06:427] Receive the 49998th response.
[15:40:06:427] Receive the 49999th response.
[15:40:07:090] Current direct memory counter : 212992 kb.
[15:40:08:090] Current direct memory counter : 212992 kb.
```

**Comment by bluelullaby** [comment]
Thanks for your reply.  I'm sorry that my expression is not clear enough.

1. Yes, your understanding is right. I mean that with sending many notifications, the value of `DIRECT_MEMORY_COUNTER` goes up quickly, but it never comes back down after stopping the pushing action.

2. Here is the condition of our production environment:
    - Running under `pushy 0.13.1` and `netty 4.1.24.Final` (In order to identify the problem, I also have tried to upgrade dependencies to `pushy 0.13.6` and `netty 4.1.28.Final`)  (Oracle Java 1.7.0_07)
    - I've added a function to log the value of `DIRECT_MEMORY_COUNTER` every 5 seconds. 
    - In each pushing action, we send a message to about 150,000 devices. (I set the value of `concurrentConnections` to 8, and pass the new instance of `NioEventLoopGroup` to the client builder, which also holds 8 threads.)
    - Changes in the value of `DIRECT_MEMORY_COUNTER` seem puzzling. The value may go up after a pushing action, but sometimes may not. 

This is the code of the initialization of the `ApnsClient` in our production environment (threadCount = 8):
```java
ApnsClient client = new ApnsClientBuilder()
        .setApnsServer(ApnsClientBuilder.PRODUCTION_APNS_HOST)
        .setClientCredentials(new File(p12File), p12Password)
        .setConcurrentConnections(threadCount)
        .setEventLoopGroup(new NioEventLoopGroup(threadCount))
        .build();
```

3. I also have done some testings to identify the problem:

This code is to log the direct memory usage.

```java
public class MemoryLeakMonitor {

    private static final Logger logger = LoggerFactory.getLogger(MemoryLeakMonitor.class);
    
    private final ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(1);

    private Field field;
    
    public MemoryLeakMonitor() {
        try {
            this.field = PlatformDependent.class.getDeclaredField("DIRECT_MEMORY_COUNTER");
            this.field.setAccessible(true);
        } catch (Exception ignore) { }
    }
    
    public void start() {
        executor.scheduleAtFixedRate(new Runnable() {
            @Override
            public void run() {
                try {
                    AtomicLong counter = (AtomicLong) field.get(null);
                    if (counter != null)
                        logger.info("Current direct memory counter : {} kb.", (counter.get() / 1024));
                } catch (Exception e) {
                    logger.error("Cannot access to the netty memory counter field!!!");
                }
            }
        }, 0, 5, TimeUnit.SECONDS);
    }
    
}
```

This code is the testing code.

```java
public class Application {

    private static final Logger logger = LoggerFactory.getLogger(Application.class);
    
    public static void main(String[] args) throws Exception {
        
        final ApnsClient apnsClient = new ApnsClientBuilder()
                .setApnsServer(ApnsClientBuilder.DEVELOPMENT_APNS_HOST)
                .setClientCredentials(new File("g:/push_apple_development.p12"), "123")
                .setConcurrentConnections(8)
                .build();
        
        MemoryLeakMonitor monitor = new MemoryLeakMonitor();
        monitor.start();

        int i = 0; // send push notifications 10000 times in total
        final AtomicLong cursor = new AtomicLong(0); // cursor of response

        for (;;) {
            
            final ApnsPayloadBuilder payloadBuilder = new ApnsPayloadBuilder();
            payloadBuilder.setAlertBody("Example!");
            
            final String payload = payloadBuilder.buildWithDefaultMaximumLength();
            
            SimpleApnsPushNotification pushNotification = 
                    new SimpleApnsPushNotification("123456789", 
                            "com.example.myApp", payload);
            
            final PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>> 
            sendNotificationFuture = apnsClient.sendNotification(pushNotification);
            
            sendNotificationFuture.addListener(new PushNotificationResponseListener<SimpleApnsPushNotification>() {

                @Override
                public void operationComplete(final PushNotificationFuture<SimpleApnsPushNotification, 
                        PushNotificationResponse<SimpleApnsPushNotification>> future) throws Exception {
                    if (future.isSuccess())
                        logger.info("Receive the {}th response.", cursor.getAndIncrement());
                    else
                        future.cause().printStackTrace();
                }
            });
            
            if (i >= 10000) {
                logger.info("Complete all sending task");
                break;
            }
            
            i++;
            
            Thread.sleep(100);
        }
    }
}
```

When I send the notifications in the low-speed condition (There is 100ms sleep time after each message), the log may like this:

```
[14:37:39:403] Native SSL provider is available; will use native provider.
[14:37:39:534] Current direct memory counter : 16384 kb.
[14:37:40:533] Current direct memory counter : 32768 kb.
[14:37:40:908] Receive the 0th response.
[14:37:40:908] Receive the 1th response.

...

[14:37:41:489] Receive the 17th response.
[14:37:41:533] Current direct memory counter : 32768 kb.
[14:37:41:577] Receive the 18th response.

...

[14:55:50:106] Current direct memory counter : 32768 kb.
[14:55:50:175] Receive the 9995th response.
[14:55:50:258] Complete all sending task
[14:55:50:262] Receive the 9996th response.
[14:55:50:368] Receive the 9997th response.
[14:55:50:468] Receive the 9998th response.
[14:55:51:106] Current direct memory counter : 32768 kb.
[14:55:52:106] Current direct memory counter : 32768 kb.
```

After `ApnsClient` is instantiated, one chunk (16MB) space has been used.
Subsequently, another chunk space is allocated for sending notifications.
Throughout the whole sending task (10,000 messages), the value of `DIRECT_MEMORY_COUNTER` don't increase.

When I comment the last line of the testing code to stop the sleeping operation, as a mass of notifications are sent simultaneously, the direct memory usage goes up, but doesn't come down after the whole sending task. The log may like this:

```
[15:15:43:910] Native SSL provider is available; will use native provider.
[15:15:44:051] Current direct memory counter : 16384 kb.
[15:15:44:278] Complete all sending task
[15:15:45:050] Current direct memory counter : 32768 kb.
[15:15:45:314] Receive the 0th response.
[15:15:45:314] Receive the 1th response.

...

[15:15:46:049] Receive the 1288th response.
[15:15:46:050] Current direct memory counter : 32768 kb.
[15:15:46:050] Receive the 1289th response.

...

[15:15:47:050] Receive the 4110th response.
[15:15:47:051] Current direct memory counter : 49152 kb.
[15:15:47:051] Receive the 4111th response.

...

[15:15:48:017] Receive the 9575th response.
[15:15:48:051] Current direct memory counter : 49152 kb.
[15:15:48:057] Receive the 9576th response.

[15:15:48:188] Receive the 9998th response.
[15:15:48:189] Receive the 9999th response.
[15:15:48:189] Receive the 10000th response.
[15:15:49:051] Current direct memory counter : 49152 kb.
[15:15:50:051] Current direct memory counter : 49152 kb.
```

With the increase of the number of messages to be sent, the memory usage goes up significantly.
This log is the case of sending 50,000 messages:

```
[15:39:57:965] Native SSL provider is available; will use native provider.
[15:39:58:091] Current direct memory counter : 16384 kb.
[15:39:58:549] Complete all sending task
[15:39:59:090] Current direct memory counter : 32768 kb.
[15:39:59:644] Receive the 0th response.
[15:39:59:644] Receive the 1th response

...

[15:40:00:031] Receive the 329th response.
[15:40:00:090] Current direct memory counter : 32768 kb.
[15:40:00:116] Receive the 330th response.

...

[15:40:01:086] Receive the 3120th response.
[15:40:01:090] Current direct memory counter : 49152 kb.
[15:40:01:174] Receive the 3121th response.

...

[15:40:02:058] Receive the 4194th response.
[15:40:02:090] Current direct memory counter : 212992 kb.
[15:40:02:189] Receive the 4195th response.

...

[15:40:06:427] Receive the 49998th response.
[15:40:06:427] Receive the 49999th response.
[15:40:07:090] Current direct memory counter : 212992 kb.
[15:40:08:090] Current direct memory counter : 212992 kb.
```

**Comment by bluelullaby** [comment]
Thanks for your reply.  I'm sorry that my expression is not clear enough.

It seems that I get an incorrect understanding about the value of `DIRECT_MEMORY_COUNTER`. 
Since the life cycle of the direct memory allocated by Netty is completely controlled by Netty itself,  it will not be released through the internal cleaner of Java.  So even the memory is released correctly, the value of `DIRECT_MEMORY_COUNTER` maybe not come down.

Previously, our production environment has occurred the following exceptions:

```
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:149)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:480)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:104)
	at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:356)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1000)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:956)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:512)
	at io.netty.handler.codec.http2.DefaultHttp2Connection.close(DefaultHttp2Connection.java:152)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$BaseDecoder.channelInactive(Http2ConnectionHandler.java:221)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1028)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:722)
```

```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 520093975, max: 524288000)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	at com.turo.pushy.apns.ApnsClientHandler.writePushNotification(ApnsClientHandler.java:206)
	at com.turo.pushy.apns.ApnsClientHandler.write(ApnsClientHandler.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:722)
```

```
io.netty.handler.codec.http2.StreamBufferingEncoder$Http2ChannelClosedException: Connection closed
	at io.netty.handler.codec.http2.StreamBufferingEncoder.close(StreamBufferingEncoder.java:228)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$BaseDecoder.channelInactive(Http2ConnectionHandler.java:216)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1028)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:722)
```

But during the test, these problems cannot be reproduced.

So I think you can close this issue. I will continue to observe the production environment for a period of time to confirm whether the above problem does exist.

At last, thanks for your reply sincerely.

**Comment by jchambers** [comment]
Let's keep this open for now. There's clearly _some_ problem here that only pops up in some yet-unknown circumstances. It's very difficult to debug, but let's see if we can get some more information.

And no worries at all on the clarity of the expression! I thought it was clear, but it's best to double-check when it comes to the finer details of a bug. Thank you for your patience in investigating the issue!

**Comment by jchambers** [comment]
For posterity, this also related to #425.

**Comment by jorcasso** [comment]
Not sure if may help, we had a similar situation when sending a huge amount of messages in a short period of time, but then we realized that pushy was buffering the messages because it has a defined in-flight window as explained here https://github.com/relayrides/pushy/wiki/Best-practices, so we implemented our own flow control to avoid pushy to buffer and we did not have that error anymore. It seems the buffered messages are holding direct memory.

**Comment by jchambers** [comment]
> It seems the buffered messages are holding direct memory.

This has been my suspicion for a while, though I still haven't found a specific mechanism by which it would happen.

**Comment by jchambers** [comment]
Checking in on this issue: is anybody still having this problem as of 0.13.11?

**Comment by barkefors** [comment]
>Checking in on this issue: is anybody still having this problem as of 0.13.11?

Nope, 👏 good job plugging it! We did hit it on 0.13.10, then moved to a local build cherry-picking https://github.com/jchambers/pushy/commit/d9743b5e50db959cc59bd0f77c3d5661fcf05a11, https://github.com/jchambers/pushy/commit/96227fe8dbaf367740683d2ccd6acb9d33ac23f9 and https://github.com/jchambers/pushy/commit/ad1a6e1b9c5d951bd8800cffbe210065977aeda4 which solved it, and still haven't observed it since moving to 0.13.11.

**Comment by jchambers** [comment]
Excellent!

I'm thrilled to hear it. Thank you for following up!
