### ISSUE TITLE
Consider adding default certificate for GeoTrust Global CA

### ISSUE THREAD

**Issue by komu** [jchambers/pushy#809]
We updated our Docker base image from OpenJDK 11 to OpenJDK 14 and our push notifications stopped working, root cause being _"sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"_.

I tested the same code on my Mac, also using OpenJDK 14, but everything worked correctly. Finally, I grabbed `/usr/local/openjdk-14/lib/security/cacerts` from the Docker image and started my test program using `-Djavax.net.ssl.trustStore=$HOME/tmp/cacerts-java14` and got the failure to reproduce locally.

I started to study the problem and found out that OpenJDK, along with browser vendors, has disabled support for GeoTrust Global CA, which is the root CA used by `api.push.apple.com`:

* https://blogs.oracle.com/java-platform-group/jdk-distrusting-symantec-tls-certificates
* https://groups.google.com/a/chromium.org/g/blink-dev/c/eUAKwjihhBs/m/El1mH8S6AwAJ?pli=1
* https://blog.mozilla.org/security/2018/03/12/distrust-symantec-tls-certificates/

However, the browser vendors seem to have [an exception](https://wiki.mozilla.org/CA/Additional_Trust_Changes#Symantec) for certificates signed by some known intermediary CAs (one being Apple's CA). I saw no evidence of such exception on JDK. Also, it seems that MacOS is configured to trust Apple's CA. Therefore, opening `api.push.apple.com` using a browser or default JDK settings on Mac works, but fails if JDK is instructed to only use `$JAVA_HOME/lib/security/cacerts`.

[Apple's APNS documentation](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1) has a note that tells one to make sure that [GeoTrust_Global_CA.pem](https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem) is trusted by the system. And sure enough: if we pass that to `ApnsClientBuilder.setTrustedServerCertificateChain`, everything works correctly.

This finally brings me to my issue: it's certainly possible to configure Pushy to work with Apple's APNS servers (I was so happy to find `setTrustedServerCertificateChain` which saved the day). And of course one could consider this to be an issue with JDK or the environment and not with Pushy.  But since OpenJDK on Docker without any extra certificates is probably a pretty common deployment target for Pushy, I think more and more people will bump into this same issue. So it would be really nice is Pushy would just work out-of-the-box. Or if messing with the default certificates feels bad, perhaps the situation could be detected and Pushy could give an informative error message with a link to the documentation?

**Comment by jchambers** [comment]
Thanks for the thoughtful report! This is certainly going to be a headache for Pushy users one way or another. Shipping with a trusted-by-default certificate feels a little gnarly to me, but so does asking everybody to manage JDK trust stores on their own (assuming they've read the docs, and history suggests that there's a significant subset of the population that doesn't).

I definitely agree that there's a problem to be solved and one of the two approaches you've suggested is likely the best way forward. I'll have to think for a bit on the specifics, though. I'll come back to this shortly, but am certainly open to suggestions in the meantime!

**Comment by jchambers** [comment]
Maybe the right thing to do is to include the certificate as a resource withing Pushy, then provide an easy—but off-by-default—way to trust that certificate via `ApnsClientBuilder`.

**Comment by eager** [comment]
I [noted this](https://groups.google.com/g/pushy-apns/c/3QF-Agee2K4) on the pushy mailing list when it first cropped up, but it seems like Debian, which is the base image for OpenJDK’s Docker image, might not have [a fix](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962596) as soon as I had hoped.

We could be even more targeted, and only trust Apple’s intermediate certificate, `Apple IST CA 2 - G1`. It doesn’t seem too aggressive to trust that by default, but I’m also not familiar with any potential tradeoffs in doing that.

**Comment by jchambers** [comment]
> It doesn’t seem too aggressive to trust that by default, but I’m also not familiar with any potential tradeoffs in doing that.

That's reasonable, too!

The two stumbling blocks in my mind:

1. Certificate expiration or (more rarely) certificate revocation. The current intermediate certificate is due to expire on May 20, 2022.
2. Outright certificate/root authority changes.

I don't recall if there's a good way to say "trust all of the stuff the OS/JDK already trusts, but add this extra thing." My memory—which could certainly be wrong, and I'll actually look into this as soon as my schedule allows—is that there isn't a great way to do so, and we have to specify the complete and exclusive list of certificates trusted within an SSL context (i.e. "trust ONLY this certificate").

If we _can_ do the additive thing, I think adding the root or intermediate certificates to the default trusted set makes sense. If it's an all-or-nothing deal, it proooobably makes more sense to leave it in users' hands.

Like I said, though: I'll look forward to getting more information shortly!

**Comment by jchambers** [comment]
It looks like the additive approach is doable, if a little clumsy. I'll take a shot at that shortly.

**Comment by jchambers** [comment]
Having explored this a bit, I think we have two viable options, and I welcome your feedback on each.

## Use an "augmented" default trust store that includes Apple's (or GeoTrust's) certificate

In this approach, `ApnsClientBuilder` would, by default, construct new `ApnsClient` instances that use a `TrustManager` that augments the system default trust store with Apple's or GeoTrust's certificate. Most users wouldn't need to make any changes to take advantage of the new trust store. At the same time, I'm worried that this approach is something of a time bomb, and we may be baiting users into a situation where Pushy will stop working without warning when Apple's/GeoTrust's certificates expire (May 20, 2022).

### Pros

1. Pushy continues to "just work" for most users.
2. Minimal changes to public API.
3. If Apple moves away from GeoTrust at some point, there's a good chance that their new CA will be in users' default trust stores and things will continue to work as expected.

### Cons

1. If users adopt this version of Pushy in an environment that doesn't already trust GeoTrust's CA and don't update, then they'll wind up in a situation where Pushy mysteriously stops working on May 20, 2022.
2. We need to put out a new release that has updated certificates whenever they're available, and there's no guarantee that will happen significantly before the current certificates' expiration.
3. Users need to actually adopt the new version of Pushy before the existing certificates expire.
4. Even though it's a reasonable one in context, we're making a security decision for users in a way they may not notice.

## Include Apple's (or GeoTrust's) certificate as an easy-to-access, manually-addable trusted certificate

In this approach, `ApnsClientBuilder` would build `ApnsClient` instances with the system trust store by default. We'd introduce something like `InputStream ApnsClientBuilder#getGeoTrustCertificate()` so users could then do something like:

```java
clientBuilder().setTrustedServerCertificateChain(clientBuilder.getGeoTrustCertificate());
```

This would require some reasonably nuanced understanding on users' part both to recognize the problem and to find the solution in the docs (ignoring, for the moment, the possibility of putting more helpful messaging in the logs). Still, it would make users active participants in moving away from a default security configuration and trusting new certificates.

### Pros

1. Users know that they're adding non-default behavior.
2. We've provided a very gentle hands-on tutorial so users know what to change if Apple's certificate situation changes abruptly.
3. Public API changes are limited to adding a new method.

### Cons

1. Users have to know that this is a thing they need to do, moving away from a "just works" ideal in some cases.
2. Certificate expiration is still an issue.

----

Either way, it seems like there's some opportunity for users to get confused either now (because things don't work out of the box) or later (when something that used to work out of the box suddenly stops working).

What do you folks think? I'm personally back to leaning toward the second approach and doing what we can to provide hints in the logs if something goes wrong, but am very open to arguments either way.

**Comment by jchambers** [comment]
I took a shot at the "make it easy, but not automatic" approach in #810. Feedback is very welcome!

**Comment by eager** [comment]
I’m very ambivalent. The first option makes so much sense. While Pushy certainly should support opting out of augmentation, it’s unfortunate to have the library not work out of the box without boilerplate—or, work initially, and then fail once it gets to deployed to an environment without the certificate.

On the other hand, I agree that making it easy, but explicitly the user’s responsibility—given the uneven support for the current GlobalTrust CA and an uncertain update timeframe—reduces the likelihood of woe in May 2022, making it the more utilitarian.

Maybe the method should be `getGeoTrustGlobalCaRootCertificateThatIsValidUntilMay2022()` :-).

**Comment by komu** [comment]
I agree that there's no really good solution, but I think the proposed PR makes sense.

As a user, it's annoying if things don't work out of the box, but it's even more annoying if they just stop working some day. If I have to make a call to add the certificate manually, I'm being made aware of the fact that this is only temporary and the code will not work indefinitely.

And of course the added error messages help a lot: when the code starts failing, it's no mystery. Now I had to spend some time digging for the root cause of the problem.

I get that `getGeoTrustGlobalCaRootCertificateThatIsValidUntilMay2022` was not a serious proposal, but perhaps the method name could benefit from some uglification? The proposed:

```java
.setTrustedServerCertificateChain(ApnsClientBuilder.getGeoTrustGlobalCaRootCertificate())
```

doesn't look "wrong enough" to me. It would be nice if the code would yell "THIS WILL EVENTUALLY BREAK" to me. Not that it's _that_ serious: I'm completely fine with the way it is.

So thanks for the quick reaction and a thought-out solution! I'm very happy we switched to Pushy some time ago.

**Comment by jchambers** [comment]
> It would be nice if the code would yell "THIS WILL EVENTUALLY BREAK" to me.

I guess we cooooould mark the method as `@Deprecated`, but I think that might cause more confusion than it prevents because we don't have a non-deprecated thing we want folks to do instead. Will think a bit on other options, but I'll plan to move forward with this approach shortly.

Thanks for the feedback, everybody!

**Comment by jchambers** [comment]
> I'm very happy we switched to Pushy some time ago.

…and thanks for the kind words, @komu!

**Comment by DCKcode** [comment]
For anyone coming across this in their Docker images based on `docker.io/library/openjdk`, we found that adding the GeoTrust certificate to the Debian base image's root certificates allowed us to resolve the issue there. [We found this PR a useful example.](https://github.com/matrix-org/sygnal/pull/141/files)

**Comment by petrdvorak** [comment]
@jchambers Sorry to weigh in a bit late on this but I don't see much difference in the suggested approaches. In either case, the developer needs to know about this issue, manage certificate expiration, perform timely Pushy updates, etc. The second option with "non-default bahavior" has one more drawback: basically, everyone who uses modern Java (it will not get any younger...) will need to write "hey, add this certificate that will expire soon". Our philosophy in similar situations is "If 80% of developers would write this code, let's make it as default".

The most correct way to solve this, though: How about we chipped in and bought Apple a new certificate for APNS from a CA with a future?

**Comment by petrdvorak** [comment]
FYI: We opened FB8962512 for this with Apple.

**Comment by edmorley** [comment]
Hi! :-)

In December 2020, the `GeoTrust Global CA` cert was removed from the Mozilla CA root certificates store:
https://bugzilla.mozilla.org/show_bug.cgi?id=1670769
https://hg.mozilla.org/projects/nss/rev/4c69d6d0cf210546bef1eed490712462b9296c62

On 2021-02-02, this change was released to all Ubuntu LTS releases, as part of the regular update of the `ca-certificates` package. For example, here's the Ubuntu 18.04 version of the update:
https://ubuntuupdates.org/package/core/bionic/main/security/ca-certificates
http://launchpad.net/ubuntu/+archive/primary/+files/ca-certificates_20201027ubuntu0.18.04.1_20210119~18.04.1.diff.gz

As such I believe this issue is going to pick up again, as these updates propagate (in Heroku's case, as of yesterday: https://devcenter.heroku.com/changelog-items/2028).

**Comment by nfranke** [comment]
On March 29, 2021 the GeoTrust certificate will no longer work. You will need to include a new root certificate. See https://developer.apple.com/news/?id=7gx0a2lp

**Comment by jchambers** [comment]
> As such I believe this issue is going to pick up again, as these updates propagate.

Thanks for the heads-up! I'm finally starting to get my feet under me again after an extreeeeemely busy January, so hope to be able to address this soon.

> On March 29, 2021 the GeoTrust certificate will no longer work.

Thanks; actually just came here to post the same. I'm not immediately clear on how widely-recognized the new issuer is (I've never heard of AAACertificateServices myself, but that doesn't mean much). It could be that the new certificate actually makes this _less_ of an issue if it's widely-supported already.

**Comment by nfranke** [comment]
The AAA Certificate Services is Comodo. The cacerts that came with JDK 8 includes the certificate, as far as I can tell. It expires 2028.

**Comment by tompson** [comment]
> The AAA Certificate Services is Comodo. The cacerts that came with JDK 8 includes the certificate, as far as I can tell. It expires 2028.

So if I am understanding this correctly, when Apple exchanges the certificate the problem we currently have with the GeoTrust certificate will go away and we do not need to change anything?

Currently I fixed all my docker images to using an older base image because of this problem (https://github.com/GoogleContainerTools/distroless/issues/545#issuecomment-731939723) - it will be possible to update them again ...

**Comment by nfranke** [comment]
> So if I am understanding this correctly, when Apple exchanges the certificate the problem we currently have with the GeoTrust certificate will go away and we do not need to change anything?

That's my guess, but it's all a bit confusing for me. They say you need both certs until the cutover date.

**Comment by jchambers** [comment]
> …when Apple exchanges the certificate the problem we currently have with the GeoTrust certificate will go away and we do not need to change anything?

Right; my wager is that Apple is making this change precisely because the GeoTrust certificate is widely untrusted at this point, and they want something that's more likely to be trusted by default (which I would describe as _entirely reasonable_).

> They say you need both certs until the cutover date.

Right; makes sense. Clients will need both so there's no gap in coverage when the cutover happens.

**Comment by fzyzcjy** [comment]
> On March 29, 2021 the GeoTrust certificate will no longer work. You will need to include a new root certificate. See https://developer.apple.com/news/?id=7gx0a2lp

Thanks! I find my production environment have errors in 3.30

**Comment by fzyzcjy** [comment]
still have problems after changing cert... any ideas? https://github.com/jchambers/pushy/issues/870

**Comment by nfranke** [comment]
I literally did nothing and mine is working. My Java installation's cacerts had the new certificate already, since it's not really a new certificate. If you are using a custom cacerts you'll have to add it.

**Comment by jchambers** [comment]
…and for posterity, we started a [discussion](https://github.com/jchambers/pushy/discussions/872) (our first github discussion!) for issues around this transition.

For us, the biggest issue was prematurely retiring the Geotrust certificate; it seems like the upstream servers are still bouncing back and forth between Geotrust and Comodo a bit (or were this morning, anyhow).

That said, my own experience dealing with this makes me think we need to try a different approach to the "add whatever certificates Apple needs" mechanism. I'm sketching out a prototype now to make sure it's not ridiculous.

**Comment by jchambers** [comment]
Well, I'm embarrassed to say that I think the need for this has passed. Apple has, in my opinion, done basically the right thing, which is "use a widely-trusted certificate." We may need something like this again in the future, but don't think we do right now. I'm going to close this for now.

Thank you all for your feedback and thoughtful discussion; I'm sorry that this didn't get out in time to be helpful to the community.

**Comment by ilyaml** [comment]
In JDK 8u31 and earlier versions, SSLv3 is enabled by default. However, Apple APNs (Push Notification service) has disabled SSLv3 support. If you are using a JDK 8 version older than 8u31, you may encounter connection failures or security issues. If you must continue using JDK 8, upgrade to the latest JDK 8 update (e.g., JDK 8u371 or newer) to ensure compatibility and security with modern protocols like TLS 1.2.
